accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='accounts'

urlpatterns=[
  # call signup page view
  path('signup/',
       views.SignUpView.as_view(),
       name='signup'),

  # call signup success page view
  path('signup_success/',
       views.SignUpSuccessView.as_view(),
       name='signup_success'),

  path('login/',
       auth_views.LoginView.as_view(template_name='login.html'),
       name='login'
       ),

  path('logout/',
       auth_views.LogoutView.as_view(template_name='logout.html'),
       name='logout'
       ),
]

photo/urls.py
from django.urls import path
from . import views

app_name='photo'
urlpatterns=[
  path('', views.IndexView.as_view(), name='index'),
  path('post/', views.CreatePhotoView.as_view(), name='post'),
  path('post_done/',
      views.PostSuccessView.as_view(),
      name='post_done'),

  # filter by category
  path('photos/<int:category>',
      views.CategoryView.as_view(),
      name = 'photos_cat'
      ),
  
  # filter by user
  path('user-list/<int:user>',
      views.UserView.as_view(),
      name = 'user_list'
      ),
  
   path('photo-detail/<int:pk>',
      views.DetailView.as_view(),
      name = 'photo_detail'
      ),
  
  path('mypage/', views.MypageView.as_view(), name = 'mypage'),

  path('photo/<int:pk>/delete/',
         views.PhotoDeleteView.as_view(),
         name = 'photo_delete'
         ),
]

photogallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('',include('accounts.urls')),
    # password reset request
    path('password_reset/',
         auth_views.PasswordResetView.as_view(
           template_name = "password_reset.html"),
         name ='password_reset'),
    
    # email sent page for pw reset
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
           template_name = "password_reset_sent.html"),
         name ='password_reset_done'),
    
    # password reset page
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(
           template_name = "password_reset_form.html"),
         name ='password_reset_confirm'),
    # pw reset completed
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(
           template_name = "password_reset_done.html"),
         name ='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):

  pass

photo/models.py
from django.db import models
from accounts.models import CustomUser

class Category(models.Model):
    # category
    title = models.CharField(
        verbose_name='category',
        max_length=20)
    
    def __str__(self):
        return self.title

class PhotoPost(models.Model):
    '''manage posted data
    '''
    # custom user: parent, PhotoPost: child
    user = models.ForeignKey(
        CustomUser,
        verbose_name='user',
        # For deletion, removing all user data
        on_delete=models.CASCADE
        )
    category = models.ForeignKey(
        Category,
        verbose_name='category',
        # Ensure not to delete the category
        on_delete=models.PROTECT
        )
    title = models.CharField(
        verbose_name='title',
        max_length=200
        )
    comment = models.TextField(
        verbose_name='comment',
        )
    image1 = models.ImageField(
        verbose_name='image1',
        upload_to = 'photos'
        )
    image2 = models.ImageField(
        verbose_name='image2',
        upload_to = 'photos',
        blank=True,
        null=True
        )
    posted_at = models.DateTimeField(
        verbose_name='Posted date',
        auto_now_add=True
        )
    
    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
  # Subclass for UserCreation
  class Meta:

    model=CustomUser

    # username, email, password, password confirmation
    fields=('username', 'email', 'password1','password2')

photo/forms.py
from django.forms import ModelForm
from .models import PhotoPost

class PhotoPostForm(ModelForm):
    '''Sub Class for ModelForm
    '''
    class Meta:
        model = PhotoPost
        fields = ['category', 'title', 'comment', 'image1', 'image2']

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignUpView(CreateView):
  form_class=CustomUserCreationForm
  # template to render
  template_name="signup.html"
  # redirected url after sign up
  success_url=reverse_lazy('accounts:signup_success')

  def form_valid(self, form):
    '''
    paremeters:
      form(django.forms.Form):
        CustomerUserCreationForm object
      return:
        HttpResponseRedirect object:
          Redirecting to success_url by returing the value from super class of form_valid()
    '''
    user=form.save()
    self.object=user

    return super().form_valid(form)

class SignUpSuccessView(TemplateView):
  template_name="signup_success.html"

photo/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import PhotoPostForm
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

from django.views.generic import TemplateView

from .models import PhotoPost

from django.views.generic import DetailView, DeleteView

class IndexView(ListView):
  template_name='index.html'
  queryset = PhotoPost.objects.order_by('-posted_at')
  # number of records per page
  paginate_by = 9

# only limited to logined users
@method_decorator(login_required, name='dispatch')
class CreatePhotoView(CreateView):
    form_class = PhotoPostForm
    # template to render
    template_name = "post_photo.html"
    # redirect url after registration
    success_url = reverse_lazy('photo:post_done')

    def form_valid(self, form): # overide from CreateView class
        # get posted data with commit=False
        postdata = form.save(commit=False)

        postdata.user = self.request.user
        postdata.save()
        # return (HttpResponseRedirect)
        return super().form_valid(form)

class PostSuccessView(TemplateView):
  template_name ='post_success.html'

class CategoryView(ListView):
    # render index.html
    template_name ='index.html'
    # number of records per page
    paginate_by = 9

    def get_queryset(self):
      category_id = self.kwargs['category']
      categories = PhotoPost.objects.filter(
        category=category_id).order_by('-posted_at')
      return categories

class UserView(ListView):
    # render index.html
    template_name ='index.html'
    # number of records each page
    paginate_by = 9

    def get_queryset(self):
      user_id = self.kwargs['user']
      user_list = PhotoPost.objects.filter(
        user=user_id).order_by('-posted_at')
      return user_list

class DetailView(DetailView):
    # render post.html
    template_name ='detail.html'
    model = PhotoPost

class MypageView(ListView):
    # render mypage.html
    template_name ='mypage.html'
    paginate_by = 9

    def get_queryset(self):
      queryset = PhotoPost.objects.filter(
        user=self.request.user).order_by('-posted_at')
      return queryset

class PhotoDeleteView(DeleteView):
    model = PhotoPost
    # render photo_detail.html
    template_name ='photo_delete.html'
    # redirect to mypage upon the completion
    success_url = reverse_lazy('photo:mypage')

    def delete(self, request, *args, **kwargs):
      return super().delete(request, *args, **kwargs)

accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="" />
    <meta
      name="author"
      content="Mark Otto, Jacob Thornton, and Bootstrap contributors"
    />
    <meta name="generator" content="Hugo 0.122.0" />
    <title>Log in</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet" />
  </head>
  <body class="text-center">
    <main class="form-signin">
      {% if form.errors %}
      <p style="color: red">Username and password do not match.</p>
      {% endif %}
      <form method="post">
        {% csrf_token %}
        <img
          class="mb-4"
          src="{% static 'img/bootstrap-logo.svg' %}"
          alt=""
          width="72"
          height="57"
        />
        <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

        <label for="Username" class="visually-hidden">User name</label>

        <input
          type="text"
          name="username"
          id="id_username"
          maxlength="150"
          autocapitalize="none"
          autocomplete="username"
          class="form-control"
          placeholder="Username"
          required
          autofocus
        />
        <label for="Password" class="visually-hidden">Password</label>

        <input
          type="password"
          name="password"
          id="id_password"
          autocomplete="current-password"
          class="form-control"
          placeholder="password"
          required
          autofocus
        />

        <input class="btn btn-primary w-100 py-2" type="submit" value="login" />
        <br /><br />
        <p><a href="{% url 'password_reset' %}">Forgot password?</a></p>
        <input type="hidden" name="next" value="{% url 'photo:index' %}" />
      </form>
    </main>
  </body>
</html>

accounts/templates/logout.html
{% extends 'base.html' %}
{% block title %}Log out{% endblock %}
{% block contents %}
<div class="container">
  <div class="row">
    <div class="col offset-4 py-4">
      <h3>You have been logged out.</h3>
      <p><a href="{% url 'photo:index' %}">To the homepage</a></p>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

      {% block contents %}
      <div class="container">
        <div class="row">
          <div class="col py-4">
            <hr>
            <h3>Would you like to reset your password?</h3>
            <p>
              Please enter your registered email address. We will send you an email with a link to reset your password shortly.
            </p>
            <br>
            <form action="" method="POST" class="text-center">
              {% csrf_token %}
              {{form}}
              <input type="submit" value="Receive an email" /><br>
            </form>
            <br>
            <a href="{% url 'photo:index' %}">Photo Gallery</a>
            <hr>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/password_reset_done.html
<!doctype html>
<html lang="en">
  <head>
    <style>
      .pad{
        background-color: lavender;
        border: solid 2px;
        padding-top: 30px;
        padding-bottom: 50px;
        padding-left: 100px;
        margin-top: 50px;
        margin-right: 70px;
        margin-left: 70px;
      }
    </style>
  </head>

  <body>
    <div class="pad">
      <h2>Your password has been reset.</h2>
      <p>
        Your new password has been set. You may go ahead and login
      </p>
      <br>
      <!-- トップページへのリンク-->
      <a href="{% url 'photo:index' %}">To the homepage of Photo Gallery</a>
    </div>
  </body>
</html>

accounts/templates/password_reset_sent.html
{% extends 'base.html' %}

{% block title %}Send password reset{% endblock %}

      {% block contents %}
      <hr>
      <div class="container">
        <div class="row">
          <div class="col offset-2 py-4">
              <h5>We have sent the password reset instructions by email. The email will arrive shortly</h5>
              <br>
              <h6>
                If you do not receive the email, please check that you have entered the registered email address and also check your spam folder.</h6>
              <br>
              <a "{% url 'photo:index' %}">Photo Gallery</a>
          </dv>
        </dv>
      </dv>
      {% endblock %}

accounts/templates/signup.html
<!-- use base template -->
{% extends 'base.html' %}

{% block title %}Sign up{% endblock %}
  {% block contents %}
  <hr>
  <div class="container">
    <div class="row">
      <div class="col offset-2">
        <h3>Sign Up</h3>
        <form method="post">
          {% csrf_token %}
          {% for field in form %}
          <p>
            {{field.label_tag}}<br>
            {{field}}
            {% if field.help_text %}
            <small style="color:gray">{{field.help_text}}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{error}}</p>
              {% endfor %}
          </p>
          {% endfor %}
          <p style="color: red">
            * Please enter your email address as it is required when you reset your password.
          </p>
          <input type="submit" value="Sign up">
        </form>
        <br>
        <p><a href="{% url 'photo:index' %}">Cancel registration and return to the homepage</a></p>
      </div>
    </div>
  </div>
  {% endblock %}

accounts/templates/signup_success.html
{% extends 'base.html' %}

{% block title %}Registration Comppleted{% endblock %}
  {% block contents %}
  <div class="container">
    <div class="row">
      <div class="col offset-4 py-4">
        <h3>Registration completed</h3>
        <p><a href="{% url 'accounts:login' %}">Log in here</a></p>
      </div>
    </div>
  </div>
{% endblock %}

photo/templates/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head><script src="../assets/js/color-modes.js"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>{% block title %}{% endblock %}</title>

    <link rel="icon" type="image/x-icon" href={% static 'assets/favicon.ico' %} />

    <!-- <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/"> -->

    

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>

    
  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>

    
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>Find your favourite!</h4>
          <p class="text-body-secondary">This is a photo-sharing site open to everyone. You can post any photo you've taken yourself! However, please ensure it belongs to a specific category. Don't forget to add a comment!</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Contact</h4>
          <ul class="list-unstyled">
            {% if user.is_authenticated %}
                <!-- when logged in-->
                <li><a href="{% url 'photo:mypage' %}"
                       class="text-white">My page</a></li>
                <li><a href="{% url 'accounts:logout' %}"
                       class="text-white">Log out</a></li>
                <li><a href="{% url 'password_reset' %}"
                       class="text-white">Reset password</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% else %}
                <!-- when not logged in-->
                <li><a href="{% url 'accounts:signup' %}"
                       class="text-white">Sign up</a></li>
                <li><a href="{% url 'accounts:login' %}"
                       class="text-white">Log in</a></li>
                <li><a href="mailto:admin@example.com"
                       class="text-white">Email me</a></li>
                {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="{% url 'photo:index %'}" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Photo Gallery</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>
{% block contents %}{% endblock %}

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Photo Gallery is &copy;Bootstrap, but please post a lot</p>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>

photo/templates/mypage.html
{% extends 'base.html' %}
{% block title %}Mypage{% endblock %}

      {% block contents %}

      {% if user.is_authenticated %}
        <br>
        <div style="text-align:center">
          <h4>{{user.username}}'s My Page</h4>
          {% if object_list.count == 0 %}
            <p>No post by {{user.username}}</p>
          {% else %}
            <p><strong>{{object_list.count}}</strong> posts</p>
          {% endif %}
          <a href="{% url 'photo:post' %}">Post new photos</a>
        </div>
        <hr>
      {% endif %}
      
      {% include "photos_list.html" %}
        
      {% include "pagination.html" %}

      {% endblock %}

photo/templates/photos_list.html
  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for record in object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <img src="{{ record.image1.url }}" class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/></img>

            <div class="card-body">
              <p class="card-text">{{record.title}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photo_detail' record.pk %}'">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary" onclick="location.href='{% url 'photo:photos_cat' category=record.category.id %}'">{{record.category.title}}</button>
                </div>
                <a href="{% url 'photo:user_list' user=record.user.id %}">
                <small class="text-body-secondary">{{record.user.username}}</small>
              </a>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>

photo/templates/photos_title.html
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Photo Gallery</h1>
      <p class="lead text-body-secondary">
        Read the comments and let your imagination wander into the world
        depicted in the photos. We look forward to seeing your wonderful
        comments and photos.
      </p>
      <p>
        {% if user.is_authenticated %}
        <a href="{% url 'photo:post' %}" class="btn btn-primary my-2">Post</a>

        <!-- Use a form to trigger a POST request for logging out -->
        <form method="post" action="{% url 'accounts:logout' %}" style="display: inline;">
          {% csrf_token %}
          <button type="submit" class="btn btn-secondary my-2">Log out</button>
        </form>
        {% else %}
        <a href="{% url 'accounts:signup' %}" class="btn btn-primary my-2">Sign up now</a>
        <a href="{% url 'accounts:login' %}" class="btn btn-secondary my-2">Already registered? Log in</a>
        {% endif %}
      </p>
    </div>
  </div>
</section>